export const Icons = {
  dashboards: require('./Icons/dashboards.png'),
  task: require('./Icons/task.png'),
  plus: require('./Icons/plus.png'),
  search: require('./Icons/search.png'),
  close: require('./Icons/close.png'),
  Default: require('./Icons/default.png'),
  Cleaning: require('./Icons/clean.png'),
  Shopping: require('./Icons/shopping.png'),
  Work: require('./Icons/work.png'),
  Exercise: require('./Icons/exercise.png'),
  Meeting: require('./Icons/meeting.png'),
  Birthday: require('./Icons/birthday.png'),
  Trip: require('./Icons/trip.png'),
  Study: require('./Icons/study.png'),
  Cooking: require('./Icons/cook.png'),
  filter: require('./Icons/filter.png'),
  leftArrow: require('./Icons/left-arrow.png'),
  empty: require('./Icons/empty.png'),
  check: require('./Icons/check.png'),
  icon: require('./Icons/animIcon.gif'),
  crash: require('./Icons/crash.png'),
};

export const fontFamily = {};
